version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: myweb-proxy
    depends_on:
      - web
      - api
      - db
  web:
    image: codenee/frontend-web:0.0.1
    ports:
      - 3000:3000
    container_name: myweb-web
  api:
    image: backend-api:latest
    ports:
      - 8001:8001
    container_name: myweb-api
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "950322"
    volumes:
      - D:/docker_container/postgresql/data/:/var/lib/postgresql/data